### ISSUE TITLE
donkey car no display URL

### ISSUE THREAD

**Issue by oit107109141** [robocarstore/donkey-car-training-on-google-colab#1]
After running
python manage.py drive
I got these

using donkey v4.1.0 ...
loading config file: /home/pi/mycar/config.py
loading personal config over-rides from myconfig.py
PiCamera loaded.. . warming camera
adding part PiCamera.
Staring Donkey Server. . . . . . you can now go to raspberrypi.local:8897 to drive your car
Adding part LocalWebController.
Adding part PilotCondition.
Adding part DriveMode.
Traceback (most recent call last):
   File "manage.py", line 171,in <module>
     drive(cfg, model path=args['--model'], model_type=args['--type'])
   File "manage.py", line 136, in drive 
     if cfg.DONKEY_GYM or cfg.DRIVE_TRAIN_TYPE == "MOCK":
AttributeError: 'Config' olject has no attribute 'DRIVE_TRAIN_TYPE'
(env) pi@raspberrypi:~/mycar $
![123456](https://user-images.githubusercontent.com/73276014/106700163-430ee100-661f-11eb-8cfd-20340bfdd814.PNG)

**Comment by sctse999** [comment]
This is an upstream (donkeycar) issue. Try dev branch of donkeycar
